name: Deploy
on: push
env:
  MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  DEPLOY_FILE: "target/||JAR_NAME||.jar"
  DEPLOY_PATH: "binaries/@DEPLOY_VER@/||CATEGORY||/||JAR_NAME||@DEPLOY_BRANCH@.jar"
  DEPLOY_PASSWORD: ${{ secrets.DeployPassword }}
  CI_ENVIRONMENT_NAME: ${{ github.ref }}

jobs:
  deploy_test:
    runs-on: self-hosted
    container:
      image: maven:3-jdk-8
      volumes:
        - /srv/secrets/mavensettings.xml:/root/.m2/settings.xml:ro
        - /srv/secrets/deploy_key:/root/.ssh/deploy_key:ro
        - /srv/secrets/gradle.properties:/root/.gradle/gradle.properties:ro
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: mvn $MAVEN_CLI_OPTS deploy
      - name: Deploy
        run: |
          rm -f deployer.sh
          wget https://dev.files.ccgn.co/devops/deployer.sh
          bash ./deployer.sh
      - name: Slack Notify
        uses: 8398a7/action-slack@v3
        continue-on-error: true
        with:
          status: ${{ job.status }}
          author_name: Build Information
          fields: repo,message,commit,author,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_WEB_HOOK_URL }}
        if: always()
